# Build a worker to create a request

## What needs to happen?

Starting point: `AcceptRequest` received an HTTP request and put it on the `Accepted` queue.

Now I need to:

-  Get the request off the `Accepted` queue (`Worker`)
-  Call a `ReceiveRequest` use case
-  If the use case succeeds, mark the job done else ensure it retries
   -  Consider perma-fail job vs. connect errors causing it to fail

`ReceiveRequest` needs to:

-  Try to get the request from the database (by id)
-  If the request exists (ok) and is not in Received status, error
-  If the request exists (ok) and is in Received status, set the request to the db result
-  If the request does not exist (isErr())
   -  Create the request from the data
   -  If create fails, error
   -  Save the request
   -  If save fails, error
-  Publish request to `Received` queue
-  If publish fails, error

## Tests

For `ReceiveRequest`

-  when the database read fails, it returns a `DatabaseError`
-  when the request exists and is not in Received status, it returns an `InvalidStatusError`
-  when the request does not exist and the data is bad, it returns a `PropsError`
   -  This case will rarely happen because `AcceptRequest` creates the request to ensure data is valid before putting it on the `Accepted` queue
-  when the request does not exist and the save fails, it returns a `DatabaseError`
-  when the request does not exists and publish fails, it returns a `QueueError` (or similar, TBD)
-  when the request exists and is Received and no failures, it returns ok and publishes to the queue but does not save the request
-  when the request does not exist and no failures, it returns ok and publishes to the queue and saves the request

For the `ReceiveWorker`

-  when the use case succeeds, it marks the job complete
-  when the use case fails due to a connection error, it requeues the job
-  when the use case fails and the request has failed > MAX_RETRIES times (ignoring connection errors), it marks the job failed

## How does the BullMQ Worker work?

-  Conceptually, it's similar to the current `Subscriber`
-  `new Worker(queueName, async (job: Job) => {}, opts?)`
-  The function in the signature is the message handler, like `Subscriber`'s `on*` methods
-  If the use case fails, the message handler will need to `throw`
   -  If the error is unrecoverable, `throw new UnrecoverableError('message')` and the job won't retry
   -  If the job should be retried, throw something else
   -  If the handler returns, the job is considered successfully completed
-  Handler is responsible for logging
-  For retries, I'll need a custom backoff function
   -  `opts` -> `{ backoffStrategy: (attemptsMade: number) => number }` where the result is how long to delay before next retry
   -  Set max retries to a very large number and rely on logic in the handler to kill jobs that have retried too many times
-  If a job will be retried, use `Job.update()` to update the job data
   -  On a connection error, increment connection error count
   -  `Job.attemptsMade` is total retries
   -  If `Job.attemptsMade - Job.data.connectionErrorCount > TBD` perma-fail the job

This means the job's data has a connect failure count plus the data. I may want to define a base definition to extend:

```typescript
export interface IEvent {
	eventData: unknown;
	connectFailureCount: number;
}
```

I'm not sure how I'll test the `Worker`.

-  `Worker.processJob(job: Job, token: string)` -- I may be able to build a job and process it
-  Maybe better, build the handler function separately and pass it as a parameter to the worker
   -  `async function handler(job: Job) { ... }`
   -  `worker = new Worker('queue', handler, opts)`
   -  Then I can test the handler without worrying about the `Worker`
   -  This approach doesn't test retry, etc., but I'm not sure how to approach retry testing in jest, so maybe that's better left for integration testing

**COMMIT: DOCS: plan a worker to read accepted and make it received**

## Worker

-  Create `receive-backup-request` directory in `backup-request/use-cases`
-  Create `AcceptedBackupRequestConsumer.ts` and `.spec.ts`
-  Sketched the consumer class; wrote a simple "console.log and return ok()" function as use case
-  Found a basic test strategy

```typescript
const queue = new mockBullMq.Queue('test-queue');

const job1 = new mockBullMq.Job(queue, 'test-name', {});
// the Job constructor is mocked, so doesn't set up data
job1.data = { connectFailureCount: 0, message: 'Goodbye World!' };
job1.attemptsMade = 99; // can test exceeding retry threshold

// another way to build the job
const job2 = {
	data: {
		connectFailureCount: 0,
		message: 'Hi World!',
	},
	attemptsMade: 0,
} as unknown as bullMq.Job;

consumer.consume(job1); // or job2
// if testing for errors, wrap consume() in a try catch and expect() in the catch
// if testing for UnrecoverableError, constructor is mocked, so in catch(e)
// expect((e as Error).constructor.name).toEqual('UnrecoverableError');
```

The key here is to put everything in the consumer so all my code is tested. The BullMq `Worker` will use `consume()` with no wrapper. If I run into a lot of duplicate code, I'll consider how to make the consumer more generic. But it's probably pretty generic now because it takes a use case in the constructor, so can work with any use case.

I have my consumer test sketched out enough to see it working. Time to build the use case, then come back and finish it.

**COMMIT: TESTS: learn how to test a consumer; draft initial receive consumer tests**

## Use case

-  Add a mapper function in the adapter to map the request to the queue
-  Add a use case shell that always returns ok

Start writing tests and get them to pass

-  [x] when the database read fails, it returns a `DatabaseError`
-  [x] when the request does not exist and the data is bad, it returns a `PropsError`
   -  This case will rarely happen because `AcceptRequest` creates the request to ensure data is valid before putting it on the `Accepted` queue
-  [x] when the request doesn't exist and the save fails, it returns a `DatabaseError`
-  [x] when the request doesn't exist and publish fails, it saves and returns an `EventBusError`
-  [x] when the request doesn't exist and no failures, it saves, publishes, and returns ok
-  [x] when the request exists and is not in Received status, it returns an `InvalidStatusError`
-  [x] when the request exists and publish fails, it does not save and it returns an `EventBusError`
-  [x] when the request exists and no failures, it does not save, publishes, and returns ok

**COMMIT: FEAT: add ReceiveBackupRequestUseCase and pass tests**

## Finish event handler

-  Finish event handler and add logging
-  Write Tests for each possible throw (retry connect, retry other, unrecoverable) and success
-  Rename consumer interface `IEventBusConsumer`

**COMMIT: FEAT: finish event handler and tests**

## Worker process

The worker will be a standalone program. Testing requires Redis running, so this is an integration test, which requires:

Infrastructure

-  Redis
-  SQL Server
-  API running to accept requests and publish Accepted message (queue: accepted-backup-requests)
-  Worker running (read accepted-backup-requests / write received-backup-requests)

The worker program requires (phase 1)

-  A TypeORM context connected to the database
-  A `TypeormBackupRequestRepo`
-  A `BmqBackupRequestEventBus`
-  A `ReceiveBackupRequestUseCase`
-  An `AcceptedBackupRequestConsumer`
-  A BullMq `Worker` to run the consumer method

In the future, add a zpages router and Express instance (defer for now; zpages may change in the future).

### Notes

Created `bmqAcceptedWorker.ts`. After a bit of error tracing, it's working. Issues I found included:

-  Consumer wants request data in `event` member, so changed `publish` to put it there
-  In the worker, consumer method must `bind()` to it's object or it will lose `this` context for the use case
-  Added `try ... catch` around consumer useCase call in case something causes it to throw
   -  I was getting throws because it was getting undefined data when I didn't have `data.event`
   -  I need to check my data better in the use case to prevent the throw (added TODO below)

**COMMIT: FEAT: add receive request worker and get it working**
